resources:
    - name: repo
      type: git
      source:
          uri: https://github.com/ginoburdea/concurse-ci-testing

jobs:
    - get: repo
      trigger: true
    - name: hello-world-job
      plan:
          - task: hello-world-task
            config:
                platform: linux
                image_resource:
                    type: registry-image
                    source:
                        repository: busybox
                run:
                    path: echo
                    args: ['Hello World!']
